// Tipos de TDR según la normativa peruana
export type TdrTipo = "BIEN" | "OBRA" | "CONSULTORIA_OBRA" | "SERVICIO";

export interface TdrField {
  key: string;
  label: string;
  type: "text" | "textarea" | "number" | "date" | "select";
  required: boolean;
  placeholder?: string;
  options?: string[];
}

// Campos comunes que se repiten en múltiples categorías
const camposComunes = {
  // En 3 categorías
  antecedentes: {
    key: "antecedentes",
    label: "Antecedentes",
    type: "textarea" as const,
    required: true,
  },
  plazo: {
    key: "plazo",
    label: "Plazo",
    type: "text" as const,
    required: true,
  },
  conformidad: {
    key: "conformidad",
    label: "Conformidad",
    type: "textarea" as const,
    required: true,
  },
  objetivoGeneral: {
    key: "objetivoGeneral",
    label: "Objetivo General",
    type: "textarea" as const,
    required: true,
  },
  objetivosEspecificos: {
    key: "objetivosEspecificos",
    label: "Objetivos Específicos",
    type: "textarea" as const,
    required: true,
  },
  descripcion: {
    key: "descripcion",
    label: "Descripción",
    type: "textarea" as const,
    required: true,
  },
  // En 2 categorías
  finalidadPublica: {
    key: "finalidadPublica",
    label: "Finalidad Pública",
    type: "textarea" as const,
    required: true,
  },
  actividadPoi: {
    key: "actividadPoi",
    label: "Actividad del POI",
    type: "text" as const,
    required: true,
  },
  denominacionContratacion: {
    key: "denominacionContratacion",
    label: "Denominación de la Contratación",
    type: "text" as const,
    required: true,
  },
  cantidad: {
    key: "cantidad",
    label: "Cantidad",
    type: "number" as const,
    required: true,
  },
  unidad: {
    key: "unidad",
    label: "Unidad",
    type: "text" as const,
    required: true,
  },
  medida: {
    key: "medida",
    label: "Medida",
    type: "text" as const,
    required: true,
  },
  objetivoContratacion: {
    key: "objetivoContratacion",
    label: "Objetivo de la Contratación",
    type: "textarea" as const,
    required: true,
  },
  objetivosContratacion: {
    key: "objetivosContratacion",
    label: "Objetivos de la Contratación",
    type: "textarea" as const,
    required: true,
  },
  otrasPenalidades: {
    key: "otrasPenalidades",
    label: "Otras Penalidades",
    type: "textarea" as const,
    required: false,
  },
  lugar: {
    key: "lugar",
    label: "Lugar",
    type: "text" as const,
    required: true,
  },
  requisitosProveedor: {
    key: "requisitosProveedor",
    label: "Requisitos del Proveedor",
    type: "textarea" as const,
    required: true,
  },
  acreditacion: {
    key: "acreditacion",
    label: "Acreditación",
    type: "textarea" as const,
    required: false,
  },
};

// Campos específicos por tipo de TDR
export const tdrFieldsByType: Record<TdrTipo, TdrField[]> = {
  BIEN: [
    camposComunes.finalidadPublica,
    camposComunes.denominacionContratacion,
    camposComunes.cantidad,
    {
      key: "muestras",
      label: "Muestras",
      type: "text",
      required: false,
    },
    camposComunes.conformidad,
    camposComunes.finalidadPublica,
    {
      key: "caracteristicas",
      label: "Características",
      type: "textarea",
      required: true,
    },
    {
      key: "material",
      label: "Material",
      type: "text",
      required: false,
    },
    {
      key: "prestacionesAccesorias",
      label: "Prestaciones Accesorias",
      type: "textarea",
      required: false,
    },
    {
      key: "formaCondicionesPago",
      label: "Forma y Condiciones de Pago",
      type: "textarea",
      required: true,
    },
    {
      key: "anticorrupcionAntisoborno",
      label: "Anticorrupción y Antisoborno",
      type: "textarea",
      required: true,
    },
    {
      key: "imagenReferencial",
      label: "Imagen Referencial",
      type: "text",
      required: false,
    },
    camposComunes.lugar,
    camposComunes.otrasPenalidades,
    camposComunes.actividadPoi,
    {
      key: "penalidadMora",
      label: "Penalidad por Mora",
      type: "textarea",
      required: false,
    },
    {
      key: "solucionControversias",
      label: "Solución de Controversias",
      type: "textarea",
      required: false,
    },
    camposComunes.plazo,
    {
      key: "caracteristicasTecnicas",
      label: "Características Técnicas",
      type: "textarea",
      required: true,
    },
    camposComunes.requisitosProveedor,
    camposComunes.antecedentes,
    {
      key: "total",
      label: "Total",
      type: "number",
      required: true,
    },
    {
      key: "responsabilidadViciosOcultos",
      label: "Responsabilidad por Vicios Ocultos",
      type: "textarea",
      required: false,
    },
    {
      key: "penalidades",
      label: "Penalidades",
      type: "textarea",
      required: false,
    },
    {
      key: "decenioIgualdad",
      label: "Decenio de la Igualdad de Oportunidades para Mujeres y Hombres",
      type: "textarea",
      required: false,
    },
    {
      key: "tecnicas",
      label: "Técnicas",
      type: "textarea",
      required: false,
    },
    {
      key: "color",
      label: "Color",
      type: "text",
      required: false,
    },
    camposComunes.medida,
    {
      key: "gestionRiesgos",
      label: "Gestión de Riesgos",
      type: "textarea",
      required: false,
    },
    camposComunes.objetivosContratacion,
    camposComunes.objetivoGeneral,
    camposComunes.objetivosEspecificos,
    {
      key: "alcanceDescripcionBienes",
      label: "Alcance y Descripción de los Bienes a Contratar",
      type: "textarea",
      required: true,
    },
    camposComunes.descripcion,
    {
      key: "perfilProveedor",
      label: "Perfil del Proveedor",
      type: "textarea",
      required: true,
    },
    camposComunes.acreditacion,
    {
      key: "medidasControlEjecucion",
      label: "Medidas de Control durante la Ejecución Contractual",
      type: "textarea",
      required: false,
    },
    {
      key: "areasCoordinarContratista",
      label: "Áreas que Coordinarán con el Contratista",
      type: "textarea",
      required: false,
    },
    {
      key: "areasResponsablesControl",
      label: "Áreas Responsables de las Medidas de Control",
      type: "textarea",
      required: false,
    },
    {
      key: "formaPago",
      label: "Forma de Pago",
      type: "textarea",
      required: true,
    },
    {
      key: "clausulaAntisoborno",
      label: "Cláusula Antisoborno",
      type: "textarea",
      required: true,
    },
    {
      key: "contratoMenor",
      label: "Contrato Menor",
      type: "text",
      required: false,
    },
    {
      key: "dependenciaSolicitante",
      label: "Dependencia Solicitante",
      type: "text",
      required: true,
    },
    {
      key: "metaPoiVinculado",
      label: "Meta del POI Vinculado",
      type: "text",
      required: false,
    },
    {
      key: "otras",
      label: "Otras",
      type: "textarea",
      required: false,
    },
    {
      key: "capacidad",
      label: "Capacidad",
      type: "text",
      required: false,
    },
    {
      key: "especificacionesTecnicas",
      label: "Especificaciones Técnicas",
      type: "textarea",
      required: true,
    },
    {
      key: "garantiaComercial",
      label: "Garantía Comercial",
      type: "textarea",
      required: false,
    },
  ],

  CONSULTORIA_OBRA: [
    {
      key: "actividades",
      label: "Actividades",
      type: "textarea",
      required: true,
    },
    {
      key: "planTrabajo",
      label: "Plan de Trabajo",
      type: "textarea",
      required: true,
    },
    {
      key: "codigo",
      label: "Código",
      type: "text",
      required: false,
    },
    camposComunes.antecedentes,
    {
      key: "procedimiento",
      label: "Procedimiento",
      type: "textarea",
      required: false,
    },
    {
      key: "item",
      label: "Ítem",
      type: "text",
      required: false,
    },
    camposComunes.actividadPoi,
    camposComunes.denominacionContratacion,
    camposComunes.finalidadPublica,
    camposComunes.objetivoContratacion,
    {
      key: "prestacionesAccesorias",
      label: "Prestaciones Accesorias a la Prestación Principal",
      type: "textarea",
      required: false,
    },
    camposComunes.plazo,
    camposComunes.conformidad,
    camposComunes.otrasPenalidades,
    {
      key: "areaUsuaria",
      label: "Área Usuaria",
      type: "text",
      required: true,
    },
    {
      key: "objetoContratacion",
      label: "Objeto de la Contratación",
      type: "textarea",
      required: true,
    },
    camposComunes.finalidadPublica,
    {
      key: "objetivosContratacion",
      label: "Objetivos de la Contratación",
      type: "textarea",
      required: true,
    },
    camposComunes.objetivoGeneral,
    camposComunes.objetivosEspecificos,
    {
      key: "planOperativoInstitucional",
      label: "Plan Operativo Institucional (POI)",
      type: "textarea",
      required: false,
    },
    {
      key: "alcancesDescripcionProyecto",
      label: "Alcances y Descripción del Proyecto",
      type: "textarea",
      required: true,
    },
    {
      key: "alcanceServicio",
      label: "Alcance del Servicio",
      type: "textarea",
      required: true,
    },
    {
      key: "descripcionDetalladaServicio",
      label: "Descripción Detallada del Servicio a Contratar",
      type: "textarea",
      required: true,
    },
    {
      key: "supervision",
      label: "Supervisión",
      type: "textarea",
      required: true,
    },
    {
      key: "funcionesGenerales",
      label: "Funciones Generales",
      type: "textarea",
      required: false,
    },
    {
      key: "funcionesEspecificas",
      label: "Funciones Específicas",
      type: "textarea",
      required: true,
    },
    {
      key: "metodologiasProcedimientos",
      label: "Metodologías, Procedimientos, Plan de Trabajo",
      type: "textarea",
      required: true,
    },
    {
      key: "garantia",
      label: "Garantía",
      type: "textarea",
      required: false,
    },
    {
      key: "sujetoObligado",
      label: "Sujeto Obligado",
      type: "text",
      required: false,
    },
    {
      key: "anexoN",
      label: "Anexo N",
      type: "text",
      required: false,
    },
    {
      key: "estructuraComponentes",
      label: "Estructura de Componentes",
      type: "textarea",
      required: false,
    },
    camposComunes.descripcion,
    camposComunes.unidad,
    {
      key: "cantidad",
      label: "Cantidad",
      type: "number",
      required: true,
    },
    {
      key: "participacion",
      label: "Participación",
      type: "text",
      required: false,
    },
    {
      key: "dias",
      label: "Días",
      type: "number",
      required: false,
    },
    {
      key: "costoParcial",
      label: "Costo Parcial",
      type: "number",
      required: false,
    },
    {
      key: "costoTotal",
      label: "Costo Total",
      type: "number",
      required: true,
    },
  ],

  OBRA: [
    {
      key: "boletaVentaElectronica",
      label: "Boleta de Venta Electrónica",
      type: "text",
      required: false,
    },
    {
      key: "ruc",
      label: "RUC",
      type: "text",
      required: true,
    },
    {
      key: "municipalidadDistrital",
      label: "Municipalidad Distrital",
      type: "text",
      required: false,
    },
    {
      key: "soles",
      label: "Soles",
      type: "text",
      required: false,
    },
    camposComunes.cantidad,
    camposComunes.unidad,
    camposComunes.medida,
    camposComunes.descripcion,
    {
      key: "valorUnitario",
      label: "Valor Unitario",
      type: "number",
      required: true,
    },
    {
      key: "descuento",
      label: "Descuento",
      type: "number",
      required: false,
    },
    {
      key: "importeVenta",
      label: "Importe de Venta",
      type: "number",
      required: true,
    },
    {
      key: "importeTotal",
      label: "Importe Total",
      type: "number",
      required: true,
    },
  ],

  SERVICIO: [
    camposComunes.finalidadPublica,
    {
      key: "confidencialidad",
      label: "Confidencialidad",
      type: "textarea",
      required: false,
    },
    camposComunes.antecedentes,
    camposComunes.actividadPoi,
    camposComunes.plazo,
    camposComunes.lugar,
    {
      key: "solucionControversias",
      label: "Solución de Controversias",
      type: "textarea",
      required: false,
    },
    {
      key: "gestionRiesgos",
      label: "Gestión de Riesgos",
      type: "textarea",
      required: false,
    },
    {
      key: "entregable",
      label: "Entregable",
      type: "textarea",
      required: true,
    },
    camposComunes.denominacionContratacion,
    {
      key: "otrasPenalidades",
      label: "Otras Penalidades",
      type: "textarea",
      required: false,
    },
    {
      key: "resolucionContrato",
      label: "Resolución del Contrato",
      type: "textarea",
      required: false,
    },
    {
      key: "clausulaCumplimiento",
      label: "Cláusula de Cumplimiento",
      type: "textarea",
      required: false,
    },
    {
      key: "entregables",
      label: "Entregables",
      type: "textarea",
      required: true,
    },
    {
      key: "propiedadIntelectual",
      label: "Propiedad Intelectual",
      type: "textarea",
      required: false,
    },
    {
      key: "anticorrupcionAntisoborno",
      label: "Anticorrupción y Antisoborno",
      type: "textarea",
      required: true,
    },
    {
      key: "responsabilidadViciosOcultos",
      label: "Responsabilidad por Vicios Ocultos",
      type: "textarea",
      required: false,
    },
    {
      key: "penalidades",
      label: "Penalidades",
      type: "textarea",
      required: false,
    },
    {
      key: "penalidadMora",
      label: "Penalidad por Mora",
      type: "textarea",
      required: false,
    },
    {
      key: "metaPresupuestaria",
      label: "Meta Presupuestaria",
      type: "text",
      required: false,
    },
    {
      key: "contratacion",
      label: "Contratación",
      type: "text",
      required: false,
    },
    camposComunes.objetivoContratacion,
    {
      key: "alcanceDescripcionServicio",
      label: "Alcance y Descripción del Servicio",
      type: "textarea",
      required: true,
    },
    {
      key: "lugarPlazoEjecucion",
      label: "Lugar y Plazo de Ejecución",
      type: "textarea",
      required: true,
    },
    camposComunes.objetivoGeneral,
    {
      key: "perfilProveedor",
      label: "Perfil del Proveedor",
      type: "textarea",
      required: true,
    },
    camposComunes.requisitosProveedor,
    camposComunes.objetivosContratacion,
    {
      key: "clausulaAntisoborno",
      label: "Cláusula Antisoborno",
      type: "textarea",
      required: true,
    },
    {
      key: "terminosReferencia",
      label: "Términos de Referencia",
      type: "textarea",
      required: true,
    },
    {
      key: "formacionAcademica",
      label: "Formación Académica",
      type: "textarea",
      required: false,
    },
    {
      key: "otrasObligacionesContratista",
      label: "Otras Obligaciones del Contratista",
      type: "textarea",
      required: false,
    },
    {
      key: "formaPago",
      label: "Forma de Pago",
      type: "textarea",
      required: true,
    },
    camposComunes.acreditacion,
    {
      key: "medidasControlEjecucion",
      label: "Medidas de Control durante la Ejecución Contractual",
      type: "textarea",
      required: false,
    },
    {
      key: "clausulaAnticorrupcionAntisoborno",
      label: "Cláusula Anticorrupción y Antisoborno",
      type: "textarea",
      required: true,
    },
    {
      key: "areaUsuariaRequiereServicio",
      label: "Área Usuaria que Requiere el Servicio",
      type: "text",
      required: true,
    },
    {
      key: "mesaPartesDigital",
      label: "Mesa de Partes Digital",
      type: "text",
      required: false,
    },
    {
      key: "mesaPartesPresencial",
      label: "Mesa de Partes Presencial",
      type: "text",
      required: false,
    },
    camposComunes.descripcion,
    {
      key: "condicionesGenerales",
      label: "Condiciones Generales",
      type: "textarea",
      required: false,
    },
    {
      key: "experiencia",
      label: "Experiencia",
      type: "textarea",
      required: true,
    },
    {
      key: "unidadOrganizacion",
      label: "Unidad de Organización",
      type: "text",
      required: false,
    },
    {
      key: "requisitosProveedorPersonal",
      label: "Requisitos del Proveedor (Personal)",
      type: "textarea",
      required: false,
    },
    camposComunes.conformidad,
    {
      key: "formaCondicionesPago",
      label: "Forma y Condiciones de Pago",
      type: "textarea",
      required: true,
    },
    {
      key: "actividades",
      label: "Actividades",
      type: "textarea",
      required: true,
    },
    {
      key: "requisitosContratacion",
      label: "Requisitos para la Contratación",
      type: "textarea",
      required: true,
    },
  ],
};

// Mapeo de tipos a etiquetas en español
export const tdrTipoLabels: Record<TdrTipo, string> = {
  BIEN: "Bien",
  OBRA: "Obra",
  CONSULTORIA_OBRA: "Consultoría de Obra",
  SERVICIO: "Servicio",
};

// Mapeo de tipos a descripciones
export const tdrTipoDescriptions: Record<TdrTipo, string> = {
  BIEN: "Contratación de bienes materiales",
  OBRA: "Contratación de obras de construcción",
  CONSULTORIA_OBRA: "Contratación de servicios de consultoría para obras",
  SERVICIO: "Contratación de servicios profesionales",
};

